### ISSUE TITLE
Exception: Latex error converting to dvi

### ISSUE THREAD

**Issue by NickLarsenNZ** [NickLarsenNZ/jupyter-manim#1]
Unable to render text. Need to install Latex. See https://github.com/blang/latex-docker/blob/master/Dockerfile.basic

```py
%%manim Equation
from manimlib.imports import *

class Equation(Scene):
    def construct(self):
        text1 = TexMobject("Function")
        self.play(Write(text1))
```

```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/manimlib/extract_scene.py", line 150, in main
    scene = SceneClass(**scene_kwargs)
  File "/usr/local/lib/python3.7/site-packages/manimlib/scene/scene.py", line 52, in __init__
    self.construct()
  File "/tmp/tmpq84x2usv.py", line 5, in construct
    text1 = TexMobject("Function")
  File "/usr/local/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 144, in __init__
    self, self.arg_separator.join(tex_strings), **kwargs
  File "/usr/local/lib/python3.7/site-packages/manimlib/mobject/svg/tex_mobject.py", line 44, in __init__
    self.template_tex_file_body
  File "/usr/local/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 19, in tex_to_svg_file
    dvi_file = tex_to_dvi(tex_file)
  File "/usr/local/lib/python3.7/site-packages/manimlib/utils/tex_file_writing.py", line 67, in tex_to_dvi
    "See log output above or the log file: %s" % log_file)
Exception: Latex error converting to dvi. See log output above or the log file: ./media/Tex/c3594d26f8032866.log
```

_no actual log file is produced_

**Comment by NickLarsenNZ** [comment]
The tex is valid, I've tested via Overleaf

```tex
\documentclass[preview]{standalone}

\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{dsfont}
\usepackage{setspace}
\usepackage{tipa}
\usepackage{relsize}
\usepackage{textcomp}
\usepackage{mathrsfs}
\usepackage{calligra}
\usepackage{wasysym}
\usepackage{ragged2e}
\usepackage{physics}
\usepackage{xcolor}
\usepackage{microtype}
\DisableLigatures{encoding = *, family = * }
%\usepackage[UTF8]{ctex}
\linespread{1}

\begin{document}

\begin{align*}
Function
\end{align*}

\end{document}
```

**Comment by NickLarsenNZ** [comment]
I added this to the Dockerfile

```Dockerfile
COPY --from=blang/latex:ctanbasic /usr/local/texlive /usr/local/texlive
ENV PATH="/usr/local/texlive/2017/bin/x86_64-linux:${PATH}"
```

And can see latex and get the version via Jupyter Lab:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/10092581/67154873-86c4d500-f35f-11e9-99df-34965a02cae2.png">

**I still get the same error.**

**Comment by NickLarsenNZ** [comment]
Running `!latex -interaction=batchmode Tex/7e6b6829d5e17776.tex` from within the notebook produces a log file with an error:

```log
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (TeX Live 2017) (preloaded format=latex 2018.1.22)  20 OCT 2019 04:34
entering extended mode
 restricted \write18 enabled.
 %&-line parsing enabled.
**Tex/7e6b6829d5e17776.tex
(./Tex/7e6b6829d5e17776.tex
LaTeX2e <2017-04-15>
Babel <3.16> and hyphenation patterns for 3 language(s) loaded.

! LaTeX Error: File `standalone.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
! Emergency stop.
<read *> 
         
l.2 ^^M
        
Here is how much of TeX's memory you used:
 11 strings out of 494922
 248 string characters out of 6180396
 45835 words of memory out of 5000000
 3426 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 10i,0n,7p,62b,8s stack positions out of 5000i,500n,10000p,200000b,80000s

No pages of output.

```

**Comment by NickLarsenNZ** [comment]
Got it working. In the end, installed a heap of packages.

I still need to figure out which ones are the minimum required.

```Dockerfile
RUN apt install -y texlive-latex-extra texlive-fonts-extra texlive-latex-recommended texlive-pictures texlive-latex-extra texlive-science texlive-font-utils texlive-extra-utils
```
